# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dee4878ba5b1fdd855e3722f036223700f4d4852bcd91464be4082137ca76f7e08f81f1e7bf4beb35803b5491ee7affea91bd2c8900ad967e1c3b533630d3c5d

test:
  secret_key_base: a260e2d3685bc24714902e973930ea275ca57ca897c3507ed710382f1157fe85b956a73cd8c161b6a5f1d477c8b2dc86aa5d12eae89a380fd75de15eb3537c50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
